import type { Metadata } from "next";
import Providers from "@/components/layout/Providers";
import Nav from "@/components/layout/Nav";
import { sanityFetch } from "@/sanity/lib/fetch";
import { NAV_QUERY, type SiteNavData } from "@/sanity/queries/siteNav";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Fallback nav data when Sanity hasn't been populated yet. */
const DEFAULT_NAV: SiteNavData = {
  primaryLinks: [
    { label: "About", href: "/about", _key: "about" },
    { label: "Services", href: "/services", _key: "services" },
    { label: "Projects", href: "/projects", _key: "projects" },
    { label: "Clients", href: "/clients", _key: "clients" },
  ],
  secondaryLinks: [
    { label: "Culture & Careers", href: "/culture-and-careers", _key: "culture" },
    { label: "Blog", href: "/blog", _key: "blog" },
    { label: "Contact", href: "/contact", _key: "contact" },
  ],
  megaMenuCompanyLinks: [
    { label: "Culture & Careers", href: "/culture-and-careers", _key: "mc-culture" },
    { label: "Blog", href: "/blog", _key: "mc-blog" },
    { label: "Contact", href: "/contact", _key: "mc-contact" },
  ],
  phone: "+44 20 0000 0000",
  email: "hello@box3projects.co.uk",
  address: "London, UK",
  contactForm: {
    namePlaceholder: "Name",
    emailPlaceholder: "Email",
    messagePlaceholder: "Message",
    submitLabel: "Send message",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await sanityFetch<SiteNavData | null>({ query: NAV_QUERY });
  const nav = navData ?? DEFAULT_NAV;

  return (
    <html lang="en">
      <body data-theme="light">
        <Nav
          primaryLinks={nav.primaryLinks}
          secondaryLinks={nav.secondaryLinks}
          megaMenuCompanyLinks={nav.megaMenuCompanyLinks}
          phone={nav.phone}
          email={nav.email}
          address={nav.address}
          contactForm={nav.contactForm}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
